### ISSUE TITLE
Translucent Status Bar

### ISSUE THREAD

**Issue by danny333** [rudsonlive/NavigationDrawer-MaterialDesign#18]
In kitkat verson can we have translucent status bar?

**Comment by rudsonlive** [comment]
Hi

It is indeed possible. Just do not even put this functionality because the
result leaves much to be desired.

But I'm already providing best solutions for it.

Thank you for contact.

Em Tue Jan 27 2015 at 04:27:49, danny333 <notifications@github.com>
escreveu:

**Comment by danny333** [comment]
thx for reply buddy, will wait for this funcatioanlity :)

**Comment by rudsonlive** [comment]
I have a new version this week. If you find an implementation that was
really very good can send me it will help a lot.

I think that's why neither Google prorpia makes this functionality in their
apps because the result is not very nice.

Thanks again for your contact friend.

I am available: D

Em Tue Jan 27 2015 at 09:40:22, danny333 <notifications@github.com>
escreveu:
