### ISSUE TITLE
[Question] Use with material design

### ISSUE THREAD

**Issue by jochem4207** [rudsonlive/NavigationDrawer-MaterialDesign#55]
Hello devs,

is it possible to use this app with material theme
  ```
  <style name="AppTheme" parent="android:Theme.Material">
```
or without extending ```
"NavigationLiveo"```
 so that it can use material theme

(Background info)
This app I'm making is for a school project. With no requirements on API level so i chose 21(or higher).

**Comment by rudsonlive** [comment]
Hello.

To use the library you have to extends the NavigationLiveo or
NavigationActionBar.

On the subject of design materials you will have no problem because the
library issue is separate from the theme of your app.

Make a test because my library is very easy to use.

Thank you.

2015-05-29 20:10 GMT-03:00 jochem4207 <notifications@github.com>:

> Hello devs,
>
> is it possible to use this app with material theme
> <br> or without extending &quot;NavigationLiveo&quot; so that it can use
> material theme</p> <p>(Background info)<br> This app I&#39
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/39>;m
> making is for a school project. With no requirements on API level so i
> chose 21(or higher).</p>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/55>.
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by jochem4207** [comment]
Hey Rudsonlive,

If I extend ```
NavigationLeo``` I get the next error:```java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) ```.

I use API V21 with main style ``` material ```. In your example you use  ```app.compat style ```. Do you have a sample or can you explain what i'm missing so it would work with material as main theme.

It's for a school project so i can share all code thats necessary. The drawer looks so awesome :+1:

**Comment by rudsonlive** [comment]
Friend you forgot to use the theme of the library.

Look at the description in the github the "In your styles.xml choose your
version:"

thank you

2015-06-06 17:12 GMT-03:00 jochem4207 <notifications@github.com>:

> Hey Rudsonlive,
>
> If I extend
> NavigationLeo I get the next error:java.lang.IllegalStateException: You
> need to use a Theme.AppCompat theme (or descendant).
>
> I use API V21 with main style material. In your example you use app.compat
> style. Do you have a sample or can you explain what i'm missing so it
> would work with material as main theme.
>
> It's for a school project so i can share all code thats necessary. The
> drawer looks so awesome [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/55#issuecomment-109644469>
> .
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>
