### ISSUE TITLE
ERROR:Attribute "statusBarBackground" has already been defined  Attribute "insetForeground" has already been defined

### ISSUE THREAD

**Issue by AshMCAbhat** [rudsonlive/NavigationDrawer-MaterialDesign#73]
After adding dependency in app getting this error

**Comment by wujun4code** [comment]
@AshMCAbhat ,Hello, this lib conflicted with [https://github.com/navasmdc/MaterialDesignLibrary](https://github.com/navasmdc/MaterialDesignLibrary), I got one similar error with Attribute:rippleColor has already been defined Attribute ,did you fix this error? 
tks.

**Comment by rudsonlive** [comment]
Thank you for contact.
Today I make this change and warn you when a new version is available.
Once again, thank you

2015-10-10 9:01 GMT-03:00 WuJun <notifications@github.com>:

> @AshMCAbhat <https://github.com/AshMCAbhat> ,Hello, this lib conflicted
> with https://github.com/navasmdc/MaterialDesignLibrary, I got one similar
> error with Attribute:rippleColor has already been defined Attribute ,did
> you fix this error?
> tks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/73#issuecomment-147081981>
> .
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by rudsonlive** [comment]
Hi.

I did an analysis and found that this problem is not with my library.
the attribute "ripplerClier" exists in the Google Library "Design support
library" and is used by FloatingActionButton.

As my library uses resources "Design support library" takes place this
conflict.

You better get in touch with desevolvedor MaterialDesignLibrary the library
and let him aware of what's going on.

And it seems to me that the problem has been resolved.
https://github.com/navasmdc/MaterialDesignLibrary/issues/341

Thank you.

2015-10-10 9:41 GMT-03:00 Rudson Lima <rudsonlive@gmail.com>:

> Thank you for contact.
> Today I make this change and warn you when a new version is available.
> Once again, thank you
>
> 2015-10-10 9:01 GMT-03:00 WuJun <notifications@github.com>:
>
>> @AshMCAbhat <https://github.com/AshMCAbhat> ,Hello, this lib conflicted
>> with https://github.com/navasmdc/MaterialDesignLibrary, I got one
>> similar error with Attribute:rippleColor has already been defined Attribute
>> ,did you fix this error?
>> tks.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/73#issuecomment-147081981>
>> .
>>
>
>
>
> --
> *Rudson Lima ( live-O )* Desenvolvedor Android
> *Contato* +55 85 87050560* - *Fortaleza-ce
> *Google Play *CepLive-O e Navigation Drawer - Live-O
> <https://play.google.com/store/apps/developer?id=Rudson+Lima>
> *Social* facebook <https://www.facebook.com/rudsonlive> | google+
> <http://google.com/+RudsonLima-O> | linkedin
> <http://br.linkedin.com/in/rudsonlive/>
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>
